/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaz;

import BaseDatos.Tienda;
import Dao.DaoTienda;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author Jose
 */
public class AgregarTienda extends javax.swing.JFrame {

    Tienda tienda = new Tienda();
    DaoTienda dao = new DaoTienda();
    
    public AgregarTienda() {
        initComponents();
        this.setLocationRelativeTo(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        label_nombre = new javax.swing.JLabel();
        label_ciudad = new javax.swing.JLabel();
        txt_nombre = new javax.swing.JTextField();
        txt_ciudad = new javax.swing.JTextField();
        button_tienda = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        atras = new javax.swing.JButton();
        imagen = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        label_nombre.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        label_nombre.setText("Nombre Tienda:");
        getContentPane().add(label_nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 100, 30));

        label_ciudad.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        label_ciudad.setText("Ciudad:");
        getContentPane().add(label_ciudad, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 130, 50, 30));
        getContentPane().add(txt_nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 80, 140, 30));
        getContentPane().add(txt_ciudad, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 130, 140, 30));

        button_tienda.setBackground(new java.awt.Color(0, 255, 0));
        button_tienda.setText("Agregar");
        button_tienda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_tiendaActionPerformed(evt);
            }
        });
        getContentPane().add(button_tienda, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 90, 100, 60));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("   AGREGAR TIENDA");
        jLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 10, 150, 40));

        atras.setBackground(new java.awt.Color(255, 102, 102));
        atras.setText("Atras");
        atras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                atrasActionPerformed(evt);
            }
        });
        getContentPane().add(atras, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, 60, -1));

        imagen.setIcon(new javax.swing.ImageIcon("C:\\Users\\Jose\\Downloads\\tienda-dibujos-animados-compras_18591-44034.jpg")); // NOI18N
        getContentPane().add(imagen, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 540, 290));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void button_tiendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_tiendaActionPerformed
        tienda.setNombre(txt_nombre.getText());
        tienda.setCiudad(txt_ciudad.getText());
        
         try {
            dao.insertarTienda(tienda);

        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage());
        }
    
    }//GEN-LAST:event_button_tiendaActionPerformed

    private void atrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_atrasActionPerformed
        this.setVisible(false);
        Menu menu = new Menu();
        menu.setVisible(true);
    }//GEN-LAST:event_atrasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AgregarTienda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AgregarTienda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AgregarTienda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AgregarTienda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AgregarTienda().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton atras;
    private javax.swing.JButton button_tienda;
    private javax.swing.JLabel imagen;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel label_ciudad;
    private javax.swing.JLabel label_nombre;
    private javax.swing.JTextField txt_ciudad;
    private javax.swing.JTextField txt_nombre;
    // End of variables declaration//GEN-END:variables
}
