
package interfaz;

import BaseDatos.Productos;
import Dao.DaoProducto;
import java.sql.SQLException;
import javax.swing.JOptionPane;


public class AgregarProducto extends javax.swing.JFrame {

    Productos producto = new Productos();
    DaoProducto dao = new DaoProducto();
    
    public AgregarProducto() {
        initComponents();
        this.setLocationRelativeTo(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        agregar = new javax.swing.JButton();
        label_tipo = new javax.swing.JLabel();
        label_marca = new javax.swing.JLabel();
        label_talla = new javax.swing.JLabel();
        txt_tipo = new javax.swing.JTextField();
        txt_marca = new javax.swing.JTextField();
        txt_talla = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        imagen = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        agregar.setBackground(new java.awt.Color(51, 204, 0));
        agregar.setText("Agregar");
        agregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregarActionPerformed(evt);
            }
        });
        getContentPane().add(agregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 120, 140, 70));

        label_tipo.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        label_tipo.setForeground(new java.awt.Color(255, 255, 255));
        label_tipo.setText("Tipo:");
        getContentPane().add(label_tipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 100, 40, 30));

        label_marca.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        label_marca.setForeground(new java.awt.Color(255, 255, 255));
        label_marca.setText("Marca:");
        getContentPane().add(label_marca, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 140, 40, 30));

        label_talla.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        label_talla.setForeground(new java.awt.Color(255, 255, 255));
        label_talla.setText("talla:");
        getContentPane().add(label_talla, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 180, -1, 30));

        txt_tipo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(txt_tipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 100, 141, 30));

        txt_marca.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(txt_marca, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 140, 140, 30));

        txt_talla.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(txt_talla, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 180, 140, 30));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("AGREGAR PRODUCTO");
        jLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 20, 160, 50));

        jButton1.setBackground(new java.awt.Color(255, 102, 102));
        jButton1.setText("Atras");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 260, -1, -1));

        imagen.setIcon(new javax.swing.ImageIcon("C:\\Users\\Jose\\Downloads\\61740802-almacén-de-la-falta-de-definición-abstracta-o-de-fondo-almacén.jpg")); // NOI18N
        imagen.setText("Agregar Producto");
        getContentPane().add(imagen, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 530, 300));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void agregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregarActionPerformed
        producto.setTipo(txt_tipo.getText());
        producto.setMarca(txt_marca.getText());
        producto.setTalla(Integer.parseInt(txt_talla.getText()));
        //producto.setTienda_asociada(Integer.parseInt(txt_tienda.getText()));
        
        try {
            dao.insertarProducto(producto);

        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage());
        }

    }//GEN-LAST:event_agregarActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.setVisible(false);
        Menu menu = new Menu();
        menu.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AgregarProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AgregarProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AgregarProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AgregarProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AgregarProducto().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton agregar;
    private javax.swing.JLabel imagen;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel label_marca;
    private javax.swing.JLabel label_talla;
    private javax.swing.JLabel label_tipo;
    private javax.swing.JTextField txt_marca;
    private javax.swing.JTextField txt_talla;
    private javax.swing.JTextField txt_tipo;
    // End of variables declaration//GEN-END:variables
}
